version: 2.1

jobs:
  veracode:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: zip -r veracode-scan-target.zip ./
      - run: curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - run: unzip -o pipeline-scan-LATEST.zip
      - run: java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --fail_on_severity="Very High, High" --file veracode-scan-target.zip
        continue-on-error: true
          
workflows:
  veracode-workflow:
    jobs:
      - veracode
