version: 2.1

jobs:
  veracode:
    docker:
      - image: cimg/base:stable
    resource_class: small

    steps:

      #checkout
      - checkout

      - run: zip -r veracode-scan-target.zip ./

      - run: curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - run: unzip -o pipeline-scan-LATEST.zip
          
workflows:
  veracode-workflow:
    jobs:
      - veracode
