version: 2.1

jobs:
  veracode:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      #checkout
      - uses: actions/checkout@v3
        with:
          repository: ''

          
workflows:
  veracode-workflow:
    jobs:
      - veracode
