version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: veracode-scanning
          base-revision: master
          config-path: .circleci/veracode.yml

