version: 2.1

jobs:
  veracode:
    docker:
      - image: cimg/base:stable
    resource_class: small

    steps:
      - checkout
      - run: zip -r veracode-scan-target.zip ./
      - run: curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - run: unzip -o pipeline-scan-LATEST.zip
      - run: curl --silent --show-error --fail -O  https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/18.4.5.1/vosp-api-wrappers-java-18.4.5.1.jar -O VeracodeJavaAPI.jar`
      - run: java -jar pipeline-scan.jar --veracode_api_id "$VERACODE_API_ID" --veracode_api_key "$VERACODE_API_KEY" --fail_on_severity="Very High, High" --file veracode-scan-target.zip
          
workflows:
  veracode-workflow:
    jobs:
      - veracode
