version: 2.1

jobs:
  veracode:
    docker:
      - image: cimg/base:stable
    resource_class: small

    steps:

    #checkout
      - checkout

          
workflows:
  veracode-workflow:
    jobs:
      - veracode
